import re
from collections import defaultdict
from urllib.parse import urljoin

import pandas as pd


class IndexFetcher:

    def __init__(self, package):

        self.package_name = package["package_name"]
        self.source_url = package["source_url"]

        self.public_key_url = package.get("public_key_url")
        self.public_key_name = package.get("public_key_name")


    def discover(self):

        package_list = pd.read_html(self.source_url)[0]

        # Clean HTML generated column names
        package_list.columns = (
            package_list.columns
            .astype(str)
            .str.replace(r"[^A-Za-z ]", "", regex=True)
            .str.strip()
        )

        # Remove duplicate columns generated by HTML tables
        package_list = package_list.loc[
            :, ~package_list.columns.duplicated()
        ]


        date_col = next(
            col for col in package_list.columns
            if "date" in col.lower()
            or "modified" in col.lower()
        )

        name_col = next(
            col for col in package_list.columns
            if col.lower() in (
                "name",
                "file name",
                "filename"
            )
        )


        # Remove parent directory
        package_list = package_list[
            package_list[name_col] != "Parent directory/"
        ]


        package_list[date_col] = pd.to_datetime(
            package_list[date_col],
            errors="coerce"
        )

        package_list.dropna(
            subset=[date_col],
            inplace=True
        )


        package_list.sort_values(
            by=date_col,
            ascending=False,
            inplace=True
        )


        releases = defaultdict(list)


        archive_regex = re.compile(
            r"\.(tar\.gz|tar\.xz|tar\.bz2|tgz)(?:\.(asc|sig))?$"
        )


        extension_regex = re.compile(
            r"\.(tar\.gz|tar\.xz|tar\.bz2|tgz)(?:\.(asc|sig))?$"
        )


        for _, row in package_list.iterrows():

            filename = row[name_col]

            if not isinstance(filename, str):
                continue


            if not archive_regex.search(filename):
                continue


            release_name = extension_regex.sub(
                "",
                filename
            )


            releases[release_name].append(
                {
                    "name": filename,
                    "url": urljoin(
                        self.source_url,
                        filename
                    ),
                    "published": row[date_col]
                }
            )


        return releases



    def fetch_releases(self, limit=2):

        releases = []

        discovered = self.discover()


        for release_name, assets in list(discovered.items())[:limit]:

            releases.append(
                {
                    "package": self.package_name,
                    "version": release_name,
                    "published": assets[0]["published"],
                    "assets": assets
                }
            )


        return releases



    def get_public_key_url(self):
        return self.public_key_url


    def get_public_key_name(self):
        return self.public_key_name